name: Publish

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022
    env:
      NODE_SEA_FUSE: "fce680ab2cc467b6e072b8b5df1996b2"
    steps:
      - run: >
          gci -r "C:/Program Files (x86)/Windows Kits/10/bin/**/x86" signtool.exe
          | Select-Object -Last 1
          | ForEach-Object {'SIGNTOOLS_EXE={0}' -f $_.FullName}
          | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run build
      - run: node --experimental-sea-config sea.config.json
      - run: node -e "require('fs').copyFileSync(process.execPath, 'build/lmc.exe')"
      - run: '& $env:SIGNTOOLS_EXE remove /s "build/lmc.exe"'
      - run: >
          npx -y postject "build/lmc.exe" NODE_SEA_BLOB "build/bundle.blob"
          --sentinel-fuse NODE_SEA_FUSE_${{ env.NODE_SEA_FUSE }}
          --overwrite
      # - run: choco install -y --no-progress rcedit
      # - run: rcedit "build/lmc.exe" --set-icon icon.ico
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/lmc.exe
  icon:
    needs: build
    runs-on: windows-2022
    steps:
      - run: Invoke-WebRequest -Uri https://www.angusj.com/resourcehacker/resource_hacker.zip -OutFile rh.zip
      - run: Expand-Archive -Path rh.zip -DestinationPath "$env:TEMP"
      - run: >
          & $env:TEMP/ResourceHacker.exe
          -open "build/lmc.exe"
          -save "generated/lmc.exe"
          -resource icon.ico
          -action modify
          -mask ICONGROUP,MAINICON,
      - uses: actions/download-artifact@v4
      - uses: actions/upload-artifact@v4
        with:
          name: generated
          path: generated/lmc.exe
  publish:
    needs: icon
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: ls -la
      - run: ls -la generated/
