name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: The version to build. Must be a semver string.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: cmake --preset msvc-debug-configure -DAPP_VERSION="${{ inputs.version }}" -DCMAKE_BUILD_TYPE="Release"
      - run: cmake --build --preset msvc-debug
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/*.exe
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - run: |
          for mod in $(ls mods); do
          (
            tempdir=$(mktemp -d)
            mkdir $tempdir/custom
            cp -r mods/$mod/custom/* $tempdir/custom
            cd $tempdir
            zip -r ${{ github.workspace }}/build/$mod.zip custom/
            rm -rf $tempdir
          )
          done
      - run: jq --slurp '.' mods/**/custom/metadata.json >> build/index.json
      - run: gh release create ${{ inputs.version }} --latest --title ${{ inputs.version }} build/*
